from Sherlock.request import Request
from Sherlock.MOSS.Languages import moss_supported_languages, format_dict
from Sherlock.MOSS.connection import Moss


def run_moss(request):
	processes = []
	reports = []
	queue = Queue()
	for language, submission_list  in request.submissions.iteritems():
		moss = Moss(language, submission_list)

		process = Process(target=moss.run, args=(queue,))
		processes.append(process)
		process.start()

		reports.append(queue.get())

	for process in processes:
		process.join()

	# reports = [('c', 'http://moss.stanford.edu/report/1345546'), ('py', 'http://moss.stanford.edu/report/123123')]
	return reports


def run(contest_data):
	# create a Request object from contest_data
	request = Request(contest_data)
	# list of reports generated by moss sectioned as per language
	# [('c', 'http://moss.stanford.edu/report/1345546'), ('py', 'http://moss.stanford.edu/report/123123')]
	request.moss_report_url = run_moss(request)